function Example_06_01
% Текстовый интерпретатор - LaTeX

figN = 0; close all;
hDoc = msword_open('Лекция №6. Текстовый интерпретатор LaTeX');

LaTeX_Str = {
    'Цепные дроби', ...
    ['$$F(x)=\frac{x^{2}}{1+\displaystyle\frac{x^{2}}{1+' ...
    '\displaystyle\frac{x^{2}}{1+\displaystyle\frac{x^{2}}{1+...}}}}$$'];
    'Определенный интеграл' ...
    {
    '$$\frac{1}{b^a\Gamma(a)}\int_{0}^{x}t^{a-1}e^{\frac{t}{b}}dt$$' ...
    '$$\frac{1}{b^a\Gamma(a)}\int\limits_{0}^{x}t^{a-1}e^{\frac{t}{b}}dt$$'
    };
    'Формула Эйлера, "связывающая" 5 основных математических констант' ...
    '$$e^{i\pi}-1=0$$';
    'Использование знака суммы', ...
    {
    '$$\sum_{n=1}^{\infty}\frac{1}{n}=\infty$$' ...
    '$$\sum\nolimits_{n=1}^{\infty}\frac{1}{n}=\infty$$'
    };
    'Контурный интеграл' ...
    '$$\oint_{\Gamma} f(s) ds$$';
    'Пределы' ...
    {
    '$$\lim_{x\rightarrow0} \frac{\sin x} {x}=1$$' ...
    '$$\min_{x\in[a,b]}f(x)$$' ...
    '$$\max_{x\notin[a,b]}f(x)$$' ...
    '$$\inf_{x\in[a,b]}f(x)$$' ...
    '$$\sup_{x\in[a,b]}f(x)$$' ...
    '$$\bigcup_{i=1}^{n+1}A_{i}$$' ...
    '$$\bigcap_{i=1}^{n+1}A_{i}$$' ...
    '$$\bigoplus_{k=1}^{\infty}\tau^{(k)}$$' ...
    '$$\bigotimes_{k\ne i}\Delta^{k}$$'
    };
    'Знак квадратного корня' ...
    {
    '$$\sqrt{1+\sqrt{1+x}}$$'
    '$$\sqrt[3]{1+\sqrt[7]{1+x}}$$'
    };
    'Различные скобки и ограничители переменного размера' ...
    {
    '$$[1+(\frac{a}{b})]^3-1$$' ...
    '$$\left[1+\left(\frac{a}{b}\right)^3\right]^{-1}$$' ...
    '$$\left\{1+\left(\frac{a}{b}\right)^3\right\}^{-1}$$' ...
    '$$\left| \frac{a}{b} \right|$$' ...
    '$$\left\| \frac{a}{b} \right\|$$' ...
    '$$\left\lfloor \frac{a}{b} \right\rfloor$$' ...
    '$$\left\langle \frac{a}{b} \right\rangle$$' ...
    '$$\left\lceil \frac{a}{b} \right\rceil$$' ...
    '$$\left. \frac{1}{1+x} \right|_{1/2}^{3/2}$$'};
    'Тригонометрические, гиперболические функции и логарифмы' ...
    {
    '$$f(x)=\sin x + \cos x + \tan x + \cot x + \arcsin x + \arccos x$$' ...
    '$$f(x)=\arctan x + \log x + \ln x + \sinh x + \cosh x + \tanh x + \coth x$$'
    };
    'Смена шрифтов для интерпретатора LaTeX' ...
    '$${\mathcal A}{\mathbf A}{\mathit A}$$';
    'Установка пробелов' ...
    {
    '$$ M \quad M \qquad M \, M \: M \; M \! M$$' ...
    '$$\int\limits_{0}^{1}xdx$$' ...
    '$$\int\limits_{0}^{1}x\,dx$$'
    };
    'Горизонтальные скобки, линии и стрелки' ...
    {
    '$$\overline{\pm\Delta\pm\Delta\pm...\pm\Delta}$$' ...
    '$$\overline{\underbrace{\pm\Delta\pm\Delta\pm...\pm\Delta}_{n}}$$' ...
    '$$\underline{1+2+...+n}$$' ...
    '$$\overrightarrow{f(x,y)+h(x,y)}+\overleftarrow{f(x,y)+h(x,y)}$$'
    };
    'Формулы в тексте и текст в формулах' ...
    {
    'If $$a=0$$ and $$b=0$$ then $$\int\limits_{a}^bf(x)dx=0$$' ...
    '$$\mbox{If } a=0 \mbox{ and } b=0 \mbox{ then } \int\limits_{a}^bf(x)dx=0$$'
    };
    'Расположение формул в несколько строк' ...
    {
    '$$\begin{array}{lll} 2x+3y&=&5 \\ 4x+y&=&5 \end{array}$$' ...
    '$$\left\{\begin{array}{lll} 2x+3y&=&5 \\ 4x+y&=&5 \end{array}\right.$$'
    };
    'Набор матриц' ...
    ['$$A=\left(\begin{array}{llll} a_{11}&a_{12}&\ldots &_{1n} \\' ...
    'a_{21}&a_{22}&\dots &_{2n} \\' ...
    '\vdots&\vdots&\ddots&\vdots \\' ...
    'a_{m1}&a_{m2}&\dots &_{mn} ' ...
    '\end{array}\right)$$']
    };
% LaTeX_Str = LaTeX_Str(end,:);
for i = 1:size(LaTeX_Str, 1)
    figN = make_LaTeX_example(figN, LaTeX_Str{i, 1}, LaTeX_Str{i, 2});
end